spring.datasource.url=jdbc:postgresql://localhost:5432/eventguard
spring.datasource.username=eventguard
spring.datasource.password=eventguard
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false